# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(378, 129)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Segoe MDL2 Assets")
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.inputValidateCPF = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Segoe MDL2 Assets")
        font.setPointSize(14)
        self.inputValidateCPF.setFont(font)
        self.inputValidateCPF.setObjectName("inputValidateCPF")
        self.gridLayout.addWidget(self.inputValidateCPF, 0, 1, 1, 1)
        self.labelOutput = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Segoe MDL2 Assets")
        font.setPointSize(28)
        self.labelOutput.setFont(font)
        self.labelOutput.setStyleSheet("color: green")
        self.labelOutput.setText("")
        self.labelOutput.setAlignment(QtCore.Qt.AlignCenter)
        self.labelOutput.setObjectName("labelOutput")
        self.gridLayout.addWidget(self.labelOutput, 3, 0, 1, 3)
        self.btnValidateCPF = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Segoe MDL2 Assets")
        font.setPointSize(14)
        self.btnValidateCPF.setFont(font)
        self.btnValidateCPF.setObjectName("btnValidateCPF")
        self.gridLayout.addWidget(self.btnValidateCPF, 0, 2, 1, 1)
        self.btnGenerateCPF = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Segoe MDL2 Assets")
        font.setPointSize(14)
        self.btnGenerateCPF.setFont(font)
        self.btnGenerateCPF.setObjectName("btnGenerateCPF")
        self.gridLayout.addWidget(self.btnGenerateCPF, 2, 0, 1, 3)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "CPF Validator and Generator"))
        self.label.setText(_translate("MainWindow", "Input CPF:"))
        self.btnValidateCPF.setText(_translate("MainWindow", "Validate"))
        self.btnGenerateCPF.setText(_translate("MainWindow", "Generate CPF"))
